name: Build

on:
  push:
  pull_request:

jobs:
   build-and-upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1  

      - name: Build
        run: msbuild "./Desktop Notes/Desktop Notes/Desktop Notes.csproj" /p:Configuration=Release /p:Platform="AnyCPU"
        shell: powershell

      - name: Create installer
        run: |
          wix build -s "./Desktop Notes/Desktop Notes/Desktop Notes.csproj" -o "./Desktop Notes/Desktop Notes/bin/Release/Install Desktop Notes.msi"
        shell: powershell
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: "Desktop Notes/Desktop Notes/bin/Release/**"

      

